#!/usr/bin/env python3
"""
Newsletter Generator
Creates formatted newsletters from top properties
"""

import json
from datetime import datetime
from pathlib import Path
import sys

# Import analyzer
from analyzer import get_top_properties

# Paths
SCRIPT_DIR = Path(__file__).parent
OUTPUT_DIR = SCRIPT_DIR / "output"

def generate_markdown(properties, date=None):
    """Generate newsletter in Markdown format"""
    if not date:
        date = datetime.now().strftime("%B %d, %Y")

    newsletter = f"""# 🏠 Melbourne Rental Picks - {date}

_Top rental properties matching your criteria_

---

## 📊 Summary

- **Total scanned:** {len(properties)} properties
- **Your budget:** ${' '.join(properties[0].get('price', '').split()[:1]) if properties else 'N/A'}/week max
- **Areas:** Lalor, Epping, Reservoir, Wollert

---

## 🌟 Top Picks

"""

    for i, prop in enumerate(properties, 1):
        price = prop.get('price', 'N/A')
        address = prop.get('address', 'N/A')
        beds = prop.get('bedrooms', 'N/A')
        baths = prop.get('bathrooms', 'N/A')
        parking = prop.get('parking', 'N/A')
        score = prop.get('score', 0)
        link = prop.get('link', '#')

        newsletter += f"""
### {i}. {address}

**💰 Price:** {price}/week
**🛏️ Bedrooms:** {beds} | **🚿 Bathrooms:** {baths} | **🚗 Parking:** {parking}
**⭐ Value Score:** {score}/100

🔗 [View Property]({link})

---

"""

    newsletter += f"""
---

## 💡 Tips

- **Act fast:** Good rentals go quickly in Melbourne
- **Prepare documents:** Have references, ID, income proof ready
- **Consider:** Slightly over budget for better location may save commute time

---

*Generated by Rental Scanner • {date}*
"""

    return newsletter

def save_newsletter(newsletter_content, date=None):
    """Save newsletter to file"""
    if not date:
        date = datetime.now().strftime("%Y-%m-%d")

    filename = f"{date}.md"
    filepath = OUTPUT_DIR / filename

    with open(filepath, 'w') as f:
        f.write(newsletter_content)

    print(f"📝 Newsletter saved to: {filepath}")
    return filepath

def main():
    """Generate and save newsletter"""
    print("="*60)
    print("📧 NEWSLETTER GENERATOR")
    print("="*60)

    # Get top properties
    properties = get_top_properties()

    if not properties:
        print("❌ No properties to include in newsletter")
        sys.exit(1)

    # Generate newsletter
    newsletter = generate_markdown(properties)

    # Save
    filepath = save_newsletter(newsletter)

    # Print preview
    print("\n" + "="*60)
    print("📋 NEWSLETTER PREVIEW")
    print("="*60)
    print(newsletter[:500] + "...\n")

    print("="*60)
    print("✅ NEWSLETTER GENERATED")
    print(f"Properties: {len(properties)}")
    print(f"File: {filepath}")
    print("="*60)

    return filepath

if __name__ == "__main__":
    main()
